(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return!0;return!1}
function getSize(a){var g=a.toLowerCase(),l=window.document,e=l.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var k=l.createElement("body");k.id="vpw-test-b";k.style.cssText="overflow:scroll";var f=l.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+g+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";k.appendChild(f);e.insertBefore(k,l.head);
a=7==f["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(k)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var g=getSize("Width"),l=Math.min(a/CANVAS_HEIGHT,g/CANVAS_WIDTH),e=CANVAS_WIDTH*l,l=CANVAS_HEIGHT*l,k;l<a?(k=a-l,l+=k,e+=CANVAS_WIDTH/CANVAS_HEIGHT*k):e<g&&(k=g-e,e+=k,l+=CANVAS_HEIGHT/CANVAS_WIDTH*k);k=a/2-l/2;var f=g/2-e/2,c=CANVAS_WIDTH/e;if(f*c<-EDGEBOARD_X||k*c<-EDGEBOARD_Y)l=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*EDGEBOARD_X)),
e=CANVAS_WIDTH*l,l*=CANVAS_HEIGHT,k=(a-l)/2,f=(g-e)/2,c=CANVAS_WIDTH/e;s_iOffsetX=-1*f*c;s_iOffsetY=-1*k*c;0<=k&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",e+"px");$("#canvas").css("height",l+"px");0>k?$("#canvas").css("top",k+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}
function createBitmap(a,g,l){var e=new createjs.Bitmap(a),k=new createjs.Shape;g&&l?k.graphics.beginFill("#fff").drawRect(0,0,g,l):k.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=k;return e}function createSprite(a,g,l,e,k,f){a=null!==g?new createjs.Sprite(a,g):new createjs.Sprite(a);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-l,-e,k,f);a.hitArea=g;return a}
function randomFloatBetween(a,g,l){"undefined"===typeof l&&(l=2);return parseFloat(Math.min(a+Math.random()*(g-a),g).toFixed(l))}function shuffle(a){for(var g=a.length,l,e;0!==g;)e=Math.floor(Math.random()*g),--g,l=a[g],a[g]=a[e],a[e]=l;return a}function formatTime(a){a/=1E3;var g=Math.floor(a/60);a=parseFloat(a-60*g).toFixed(1);var l="",l=10>g?l+("0"+g+":"):l+(g+":");return 10>a?l+("0"+a):l+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);a.dispatchEvent(g)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var g=window.location.search.substring(1).split("&"),l=0;l<g.length;l++){var e=g[l].split("=");if(e[0]==a)return e[1]}}
function CSpriteLibrary(){var a,g,l,e,k,f;this.init=function(c,d,h){l=g=0;e=c;k=d;f=h;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},g++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){k.call(f)};this._onSpriteLoaded=function(){e.call(f);++l===g&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return g}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=640,EDGEBOARD_X=300,EDGEBOARD_Y=0,FONT_GAME="adonaisregular",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=380,REEL_OFFSET_Y=118,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=10,
WILD_SYMBOL=10,BONUS_SYMBOL=9,NUM_PAYLINES=5,SYMBOL_SIZE=140,SPACE_BETWEEN_SYMBOLS=10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,MIN_BET,MAX_BET,TOTAL_MONEY,MAX_NUM_HOLD,BONUS_ITEM_WIDTH=304,BONUS_ITEM_HEIGHT=250,NUM_PRIZES=3,NUM_SYMBOLS_FOR_BONUS,PERC_WIN_PRIZE_1,PERC_WIN_PRIZE_2,PERC_WIN_PRIZE_3,SOUNDTRACK_VOLUME=.5,WIN_OCCURRENCE,SLOT_CASH,MIN_WIN,BONUS_OCCURRENCE,BONUS_PRIZE=
[[5,50,200],[50,200,500],[100,500,1E3]];
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolWin();this._initSymbolAnims();this._initSymbolsOccurence();this._initBonus()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var g={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(g)}};this._initPaylines=
function(){s_aPaylineCombo=[[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}]]};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,
1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,
images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,
height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_9_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[8]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_10_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
14]}};s_aSymbolAnims[9]=new createjs.SpriteSheet(a)};this._initSymbolWin=function(){s_aSymbolWin=[[0,0,150,250,500],[0,0,100,150,200],[0,0,50,100,150],[0,10,20,50,100],[0,10,25,50,100],[0,5,15,25,50],[0,2,10,20,35],[0,1,5,10,15],[0,1,5,10,15]]};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);
for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;7>a;a++)s_aRandSymbols.push(7);for(a=0;7>a;a++)s_aRandSymbols.push(8);for(a=0;2>a;a++)s_aRandSymbols.push(9);for(a=0;2>a;a++)s_aRandSymbols.push(10)};this._initBonus=function(){s_aPrizeOccurence=[];var a;for(a=0;a<PERC_WIN_PRIZE_1;a++)s_aPrizeOccurence.push(0);for(a=0;a<PERC_WIN_PRIZE_2;a++)s_aPrizeOccurence.push(1);for(a=0;a<PERC_WIN_PRIZE_3;a++)s_aPrizeOccurence.push(2)};this._init()}
var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols,s_aPrizeOccurence;TEXT_MONEY="MONEY";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";TEXT_SPIN="SPIN";TEXT_WIN="WIN";TEXT_HOLD="HOLD";TEXT_HELP_WILD="JOLLY SYMBOL CAN REPLACE ANY OTHER SYMBOL TO MAKE UP A COMBO";TEXT_HELP_BONUS="3 OR MORE PYRAMIDS LET YOU PLAY THE BONUS GAME!";TEXT_CONGRATULATIONS="Congratulations!";TEXT_MSG_SHARE1="You collected <strong>";
TEXT_MSG_SHARE2=" points</strong>!<br><br>Share your score with your friends!";TEXT_MSG_SHARING1="My score is ";TEXT_MSG_SHARING2=" points! Can you do better?";
function CPreloader(){var a,g,l,e,k,f,c;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("preloader_bar","./sprites/preloader_bar.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();c=new createjs.Container;s_oStage.addChild(c)};this.unload=function(){c.removeAllChildren()};this.hide=function(){var a=
this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var d=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));c.addChild(d);d=s_oSpriteLibrary.getSprite("preloader_bar");l=createBitmap(d);l.x=510;l.y=CANVAS_HEIGHT-131;c.addChild(l);e=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));
e.x=511;e.y=CANVAS_HEIGHT-130;c.addChild(e);a=d.width;k=new createjs.Shape;k.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-130,1,30);c.addChild(k);e.mask=k;g=new createjs.Text("","24px "+FONT_GAME,"#fff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT-108;g.shadow=new createjs.Shadow("#000",2,2,2);g.textBaseline="alphabetic";g.textAlign="center";c.addChild(g);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;c.addChild(f)};this.refreshLoader=
function(c){g.text=c+"%";k.graphics.clear();c=Math.floor(c*a/100);k.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-130,c,30)};this._init()}
function CMain(a){var g,l=0,e=0,k=STATE_LOADING,f,c,d;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;c=new CPreloader};
this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();g=!0};this.soundLoaded=function(){l++;l===e&&(c.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg",
"press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/reels.ogg","reels"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel",6),createjs.Sound.registerSound("./sounds/choose_bonus_item.ogg","choose_bonus_item"),createjs.Sound.registerSound("./sounds/press_hold.ogg","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/reels.mp3","reels"),createjs.Sound.registerSound("./sounds/reel_stop.mp3","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.mp3","start_reel",6),createjs.Sound.registerSound("./sounds/choose_bonus_item.mp3","choose_bonus_item"),createjs.Sound.registerSound("./sounds/press_hold.mp3",
"press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack")),e+=8)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.jpg");s_oSpriteLibrary.addSprite("but_play_bg","./sprites/but_play_bg.png");
s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but","./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg",
"./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hit_area_col","./sprites/hit_area_col.png");s_oSpriteLibrary.addSprite("hold_col","./sprites/hold_col.png");s_oSpriteLibrary.addSprite("bonus_bg","./sprites/bonus_bg.jpg");s_oSpriteLibrary.addSprite("bonus_item","./sprites/bonus_item.png");s_oSpriteLibrary.addSprite("bonus_prize","./sprites/bonus_prize.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+
a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/payline_"+a+".png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){l++;c.refreshLoader(Math.floor(l/e*100));l===e&&(c.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=
function(){new CMenu;k=STATE_MENU};this.gotoGame=function(){d=new CGame(f);k=STATE_GAME};this.gotoHelp=function(){new CHelp;k=STATE_HELP};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==g){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=
b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);k===STATE_GAME&&d.update();s_oStage.update(a)}};s_oMain=this;f=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null;
function CTextButton(a,g,l,e,k,f,c){var d,h,b,n,t,p,q,v;this._init=function(a,c,e,f,g,k,l){d=!1;n=[];t=[];v=createBitmap(e);h=e.width;b=e.height;q=new createjs.Text(f,"bold "+l+"px "+g,k);q.textAlign="center";q.shadow=new createjs.Shadow("#000",2,2,2);q.textBaseline="middle";q.lineHeight=24;q.x=e.width/2;q.y=e.height/2;p=new createjs.Container;p.x=a;p.y=c;p.regX=e.width/2;p.regY=e.height/2;p.addChild(v,q);p.cursor="pointer";s_oStage.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown");
p.off("pressup");s_oStage.removeChild(p)};this.setVisible=function(a){p.visible=a};this.enable=function(){d=!1;v.filters=[];v.cache(0,0,h,b)};this.disable=function(){d=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);v.filters=[new createjs.ColorMatrixFilter(a)];v.cache(0,0,h,b)};this._initListener=function(){oParent=this;p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){n[a]=b;t[a]=c};this.buttonRelease=function(){d||
(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),p.scaleX=1,p.scaleY=1,n[ON_MOUSE_UP]&&n[ON_MOUSE_UP].call(t[ON_MOUSE_UP]))};this.buttonDown=function(){d||(p.scaleX=.9,p.scaleY=.9,n[ON_MOUSE_DOWN]&&n[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){p.x=a;p.y=b};this.changeText=function(a){q.text=a};this.setX=function(a){p.x=a};this.setY=function(a){p.y=a};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};
this._init(a,g,l,e,k,f,c);return this}
function CGfxButton(a,g,l,e){var k,f,c,d,h,b,n;this._init=function(a,b,e,g){k=!1;d=[];h=[];n=createBitmap(e);n.x=a;n.y=b;f=e.width;c=e.height;n.regX=e.width/2;n.regY=e.height/2;n.cursor="pointer";!1!==g&&s_oStage.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown",this.buttonDown);n.off("pressup",this.buttonRelease);s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){k=!1;n.filters=[];n.cache(0,0,f,c)};this.disable=function(){k=!0;var a=
(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);n.filters=[new createjs.ColorMatrixFilter(a)];n.cache(0,0,f,c)};this._initListener=function(){n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;h[a]=c};this.addEventListenerWithParams=function(a,c,e,f){d[a]=c;h[a]=e;b=f};this.buttonRelease=function(){k||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),n.scaleX=1,n.scaleY=1,d[ON_MOUSE_UP]&&
d[ON_MOUSE_UP].call(h[ON_MOUSE_UP],b))};this.buttonDown=function(){k||(n.scaleX=.9,n.scaleY=.9,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],b))};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this.getSprite=function(){return n};this._init(a,g,l,e);return this}
function CToggle(a,g,l){var e,k,f;this._init=function(a,d,h){e=[];k=[];var b=new createjs.SpriteSheet({images:[h],frames:{width:h.width/2,height:h.height,regX:h.width/2/2,regY:h.height/2},animations:{on:[0,1],off:[1,2]}});f=s_bAudioActive?createSprite(b,"on",h.width/2/2,h.height/2,h.width/2,h.height):createSprite(b,"off",h.width/2/2,h.height/2,h.width/2,h.height);f.x=a;f.y=d;f.stop();f.cursor="pointer";s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);
f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.setPosition=function(a,d){f.x=a;f.y=d};this.addEventListener=function(a,d,h){e[a]=d;k[a]=h};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");f.scaleX=1;f.scaleY=1;(s_bAudioActive=!s_bAudioActive)?f.gotoAndStop("on"):f.gotoAndStop("off");e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};
this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this._init(a,g,l)}
function CBetBut(a,g,l){var e,k,f,c=[],d;this._init=function(a,b,c){e=!1;k=[];f=[];c=s_oSpriteLibrary.getSprite("bet_but");var g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});d=createSprite(g,"on",0,0,c.width/2,c.height);d.stop();d.x=a;d.y=b;d.regX=c.width/2;d.regY=c.height/2;d.cursor="pointer";s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);
s_oStage.removeChild(d)};this.disable=function(a){e=a};this.setVisible=function(a){d.visible=a};this.setOn=function(){d.gotoAndStop("on")};this.setOff=function(){d.gotoAndStop("off")};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){k[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,b,d,e){k[a]=b;f[a]=d;c=e};this.buttonRelease=function(){k[ON_MOUSE_UP]&&!1===e&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("press_but"),k[ON_MOUSE_UP].call(f[ON_MOUSE_UP],c))};this.buttonDown=function(){k[ON_MOUSE_DOWN]&&!1===e&&k[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],c)};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,g,l)}
function CMenu(){var a,g,l,e,k,f;this._init=function(){l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(l);var c=s_oSpriteLibrary.getSprite("but_play_bg");e=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,c,TEXT_PLAY,FONT_GAME,"#ffde00",58);e.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-c.width/2+20,g=c.height/2+20,k=new CToggle(a,g,c),k.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),null===s_oSoundTrack?s_oSoundTrack=createjs.Sound.play("soundtrack",{volume:SOUNDTRACK_VOLUME,loop:-1}):s_oSoundTrack.volume=1;f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},600).call(function(){f.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(c,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(a-c,d+g)};this.unload=function(){e.unload();
e=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var g=!1,l,e,k,f,c,d,h,b,n,t,p,q,v,w=0,y,A,x,u,B,z,G,m,D,H,F,E,M,I,J,K,r,C=null,L;this._init=function(){k=GAME_STATE_IDLE;l=!0;x=v=d=f=0;G=[0,1,2,3,4];c=G[0];h=NUM_PAYLINES;q=TOTAL_MONEY;t=MIN_BET;p=t*h;m=[];for(var a=0;a<NUM_ROWS;a++){m[a]=[];for(var b=0;b<NUM_REELS;b++)m[a][b]=0}s_oTweenController=new CTweenController;J=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(J);this._initReels();K=createBitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oStage.addChild(K);
this._initStaticSymbols();this._initHitAreaColumn();r=new CInterface(t,p,q);L=new CBonusPanel;C=new CPayTablePanel;q<p&&r.disableSpin();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.volume=.4;g=!0};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.stop(),s_oSoundTrack=null;s_oStage.removeChild(J);s_oStage.removeChild(K);r.unload();C.unload();for(var a=0;a<u.length;a++)u[a].unload();for(a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)B[a][b].unload();L.unload()};
this._initReels=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y,c=0;u=[];for(var d=0;d<NUM_REELS;d++)u[d]=new CReelColumn(d,a,b,c),u[d+NUM_REELS]=new CReelColumn(d+NUM_REELS,a,b+SYMBOL_SIZE*NUM_ROWS,c),a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS,c+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y;B=[];for(var c=0;c<NUM_ROWS;c++){B[c]=[];for(var d=0;d<NUM_REELS;d++){var e=new CStaticSymbolCell(c,d,a,b);B[c][d]=e;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;b+=SYMBOL_SIZE}};
this._initHitAreaColumn=function(){E=[];F=[];for(var a=376,b=116,c=0;c<NUM_REELS;c++){var d=createBitmap(s_oSpriteLibrary.getSprite("hold_col"));d.x=a;d.y=b;d.visible=!1;s_oStage.addChild(d);a+=150;F.push(d);E[c]=!1}D=[];H=[];for(var a=381,b=108,c=s_oSpriteLibrary.getSprite("hit_area_col"),d=0;d<NUM_REELS;d++){var e=new createjs.Text(TEXT_HOLD,"30px "+FONT_GAME,"#ffffff");e.visible=!1;e.x=a+c.width/2;e.y=b+c.height-20;e.shadow=new createjs.Shadow("#000",1,1,2);e.textAlign="center";s_oStage.addChild(e);
D[d]=e;e=new CGfxButton(a+c.width/2,b+c.height/2,c);e.setVisible(!1);e.addEventListenerWithParams(ON_MOUSE_UP,this._onHitAreaCol,this,{index:d});a+=150;H.push(e)}};this.generateFinalSymbols=function(){for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)!1===u[b].isHold()&&(m[a][b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]);a=this._checkForCombos();this._checkForBonus();return a};this._checkForCombos=function(){z=[];for(var a=y=0;a<h;a++){var b=s_aPaylineCombo[a],c=[],d=m[b[0].row][b[0].col];
if(d!==BONUS_SYMBOL){var e=1,f=1;for(c.push({row:b[0].row,col:b[0].col,value:m[b[0].row][b[0].col]});d===WILD_SYMBOL&&f<NUM_REELS;)e++,d=m[b[f].row][b[f].col],c.push({row:b[f].row,col:b[f].col,value:m[b[f].row][b[f].col]}),f++;for(;f<b.length;f++)if(m[b[f].row][b[f].col]===d||m[b[f].row][b[f].col]===WILD_SYMBOL){if(m[b[f].row][b[f].col]===BONUS_SYMBOL)break;e++;c.push({row:b[f].row,col:b[f].col,value:m[b[f].row][b[f].col]})}else break;0<s_aSymbolWin[d-1][e-1]&&(y+=s_aSymbolWin[d-1][e-1],z.push({line:a+
1,amount:s_aSymbolWin[d-1][e-1],num_win:e,value:d,list:c}))}}return 0<z.length?!0:!1};this._checkForBonus=function(){e=!1;w=0;for(var a=[],b=0;b<NUM_ROWS;b++)for(var c=0;c<NUM_REELS;c++)m[b][c]===BONUS_SYMBOL&&(a.push({row:b,col:c,value:m[b][c]}),w++);w>=NUM_SYMBOLS_FOR_BONUS&&(z.push({line:-1,amount:0,num_win:w,value:BONUS_SYMBOL,list:a}),5<w&&(w=5),e=!0)};this._generateRandSymbols=function(){for(var a=[],b=0;b<NUM_ROWS;b++)a[b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)];return a};
this.reelArrived=function(a,b){if(f>MIN_REEL_LOOPS)if(c===b){if(!1===u[a].isReadyToStop()){var d=a;a<NUM_REELS?(d+=NUM_REELS,u[d].setReadyToStop(),u[a].restart([m[0][a],m[1][a],m[2][a]],!0)):(d-=NUM_REELS,u[d].setReadyToStop(),u[a].restart([m[0][d],m[1][d],m[2][d]],!0))}}else u[a].restart(this._generateRandSymbols(),!1);else u[a].restart(this._generateRandSymbols(),!1),0===a&&f++};this.increaseReelLoops=function(){f+=2};this.stopNextReel=function(){d++;0===d%2&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("reel_stop",{volume:.3}),c=G[d/2],d===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||M.stop();d=f=0;c=G[0];for(var a=0;a<NUM_REELS;a++)E[a]=!1,F[a].visible=!1,u[a].setHold(!1),u[a+NUM_REELS].setHold(!1);v=0;if(0<z.length){for(var h=0;h<z.length;h++){C.highlightCombo(z[h].value,z[h].num_win);-1!==z[h].line&&r.showLine(z[h].line);for(var g=z[h].list,a=0;a<g.length;a++)B[g[a].row][g[a].col].show(g[a].value)}y*=
t;q+=y;SLOT_CASH-=y;0<y&&(r.refreshMoney(q),r.refreshWinText(y));b=0;k=GAME_STATE_SHOW_ALL_WIN;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)I=createjs.Sound.play("win")}else l&&this.enableColumnHitArea(),r.refreshWinText(0),k=GAME_STATE_IDLE;!1===l&&(l=!0);!1===e&&(r.disableBetBut(!1),r.enableGuiButtons());q<p&&r.disableSpin();x++;x===A&&(x=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",q)};this.hidePayTable=function(){C.hide()};this._showWin=function(){var a;if(0<n){!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||I.stop();-1!==z[n-1].line&&(a=z[n-1].line,r.hideLine(a));a=z[n-1].list;for(var b=0;b<a.length;b++)B[a[b].row][a[b].col].stopAnim()}n===z.length&&(n=0);-1!==z[n].line&&(a=z[n].line,r.showLine(a));a=z[n].list;for(b=0;b<a.length;b++)B[a[b].row][a[b].col].show(a[b].value);n++};this._hideAllWins=function(){for(var a=0;a<z.length;a++)for(var c=z[a].list,d=0;d<c.length;d++)B[c[d].row][c[d].col].stopAnim();r.hideAllLines();n=b=0;b=TIME_SHOW_WIN;k=GAME_STATE_SHOW_WIN;
e&&L.show(w)};this.enableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)D[a].visible=!0,H[a].setVisible(!0)};this.disableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)D[a].visible=!1,H[a].setVisible(!1)};this.activateLines=function(a){h=a;this.removeWinShowing();p=a=t*h;r.refreshTotalBet(p);r.refreshNumLines(h);a>q?r.disableSpin():r.enableSpin()};this.addLine=function(){h===NUM_PAYLINES?h=1:h++;var a=t*h;p=a;r.refreshTotalBet(p);r.refreshNumLines(h);a>q?r.disableSpin():r.enableSpin()};
this.changeCoinBet=function(){var a=Math.floor(100*(t+.05))/100;a>MAX_BET?(t=MIN_BET,p=t*h,r.refreshBet(t),r.refreshTotalBet(p),a=p):(a*=h,t+=.05,t=Math.floor(100*t)/100,p=a,r.refreshBet(t),r.refreshTotalBet(p));a>q?r.disableSpin():r.enableSpin()};this.onMaxBet=function(){var a=MAX_BET;h=NUM_PAYLINES;a*=h;t=MAX_BET;p=a;r.refreshBet(t);r.refreshTotalBet(p);r.refreshNumLines(h);a>q?r.disableSpin():(r.enableSpin(),this.onSpin())};this._onHitAreaCol=function(a){a=a.index;!0===E[a]?(E[a]=!1,F[a].visible=
!1,D[a].visible=!0,v--,u[a].setHold(!1),u[a+NUM_REELS].setHold(!1)):v<MAX_NUM_HOLD&&(E[a]=!0,v++,F[a].visible=!0,D[a].visible=!1,u[a].setHold(!0),u[a+NUM_REELS].setHold(!0),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_hold"));l=!1};this.removeWinShowing=function(){C.resetHighlightCombo();r.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)B[a][b].hide();for(a=0;a<u.length;a++)u[a].activate();k=GAME_STATE_IDLE};this.endBonus=function(a){q+=a;r.refreshMoney(q);
SLOT_CASH-=a;r.disableBetBut(!1);r.enableGuiButtons()};this.onSpin=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)I&&I.stop(),M=createjs.Sound.play("reels",{volume:.3});this.disableColumnHitArea();r.disableBetBut(!0);this.removeWinShowing();MIN_WIN=s_aSymbolWin[0][s_aSymbolWin[0].length-1];for(var a=0;a<s_aSymbolWin.length;a++)for(var b=s_aSymbolWin[a],c=0;c<b.length;c++)0!==b[c]&&b[c]<MIN_WIN&&(MIN_WIN=b[c]);MIN_WIN*=t;q-=p;r.refreshMoney(q);SLOT_CASH+=p;if(SLOT_CASH<MIN_WIN){do a=this.generateFinalSymbols();
while(!0===a)}else if(Math.floor(100*Math.random())>WIN_OCCURRENCE){b=0;do a=this.generateFinalSymbols(),b++;while(!0===a&&1E4>b);if(1E4<=b)return}else this._assignWin();r.hideAllLines();r.disableGuiButtons();k=GAME_STATE_SPINNING};this._assignWin=function(){if(SLOT_CASH<BONUS_PRIZE[0][0]){var a=0;do{var b=this.generateFinalSymbols();a++}while((!1===b||y*t>SLOT_CASH||e)&&1E4>=a)}else if(Math.floor(100*Math.random())>BONUS_OCCURRENCE){a=0;do b=this.generateFinalSymbols(),a++;while((!1===b||y*t>SLOT_CASH||
e)&&1E4>=a)}else{a=0;do{var b=this.generateFinalSymbols(),c=0;e&&(c=w-3);a++}while((!1===b||y*t>SLOT_CASH||!1===e||BONUS_PRIZE[c][0]>SLOT_CASH)&&1E4>=a)}if(1E4<a){do b=this.generateFinalSymbols();while(!0===b)}};this.onInfoClicked=function(){k!==GAME_STATE_SPINNING&&(C.isVisible()?C.hide():C.show())};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",{img:"200x200.jpg",title:TEXT_CONGRATULATIONS,msg:TEXT_MSG_SHARE1+q+TEXT_MSG_SHARE2,
msg_share:TEXT_MSG_SHARING1+q+TEXT_MSG_SHARING2})};this.getState=function(){return k};this.update=function(){if(!1!==g)switch(k){case GAME_STATE_SPINNING:for(var a=0;a<u.length;a++)u[a].update(c);break;case GAME_STATE_SHOW_ALL_WIN:b+=s_iTimeElaps;b>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:b+=s_iTimeElaps,b>TIME_SHOW_WIN&&(b=0,this._showWin())}};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;SLOT_CASH=a.slot_cash;BONUS_OCCURRENCE=a.bonus_occurrence;MIN_REEL_LOOPS=a.min_reel_loop;
REEL_DELAY=a.reel_delay;TIME_SHOW_WIN=a.time_show_win;TIME_SHOW_ALL_WINS=a.time_show_all_wins;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MAX_NUM_HOLD=a.max_hold;PERC_WIN_PRIZE_1=a.perc_win_prize_1;PERC_WIN_PRIZE_2=a.perc_win_prize_2;PERC_WIN_PRIZE_3=a.perc_win_prize_3;NUM_SYMBOLS_FOR_BONUS=a.num_symbol_bonus;A=a.num_spin_ads_showing;new CSlotSettings;this._init()}var s_oGame,s_oTweenController;
function CReelColumn(a,g,l,e){var k,f,c,d,h,b,n,t,p,q,v,w,y,A,x;this._init=function(a,e,g,l){d=c=f=k=!1;t=0;h=a;n=l;b=h<NUM_REELS?h:h-NUM_REELS;q=0;v=MAX_FRAMES_REEL_EASE;p=REEL_STATE_START;w=g;y=w+SYMBOL_SIZE*NUM_ROWS;this.initContainer(e,g)};this.initContainer=function(a,b){x=new createjs.Container;x.x=a;x.y=b;var c=0;A=[];for(var d=0;d<NUM_ROWS;d++){var e=createSprite(s_aSymbolData[s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);e.stop();e.x=
0;e.y=c;x.addChild(e);A[d]=e;c+=SYMBOL_SIZE}s_oStage.addChild(x)};this.unload=function(){s_oStage.removeChild(x)};this.activate=function(){w=x.y;y=w+SYMBOL_SIZE*NUM_ROWS;k=!0};this._setSymbol=function(a){x.removeAllChildren();for(var b=0,c=0;c<a.length;c++){var d=new createSprite(s_aSymbolData[a[c]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);d.stop();d.x=0;d.y=b;x.addChild(d);A[c]=d;b+=SYMBOL_SIZE}};this.setHold=function(a){d=a};this.restart=function(a,b){x.y=w=REEL_START_Y;y=w+SYMBOL_SIZE*NUM_ROWS;this._setSymbol(a);
if(f=b){q=0;v=MAX_FRAMES_REEL_EASE;p=REEL_STATE_STOP;for(var d=0;d<NUM_ROWS;d++)A[d].gotoAndStop("static");c=!0}else for(d=0;d<NUM_ROWS;d++)A[d].gotoAndStop("moving")};this.setReadyToStop=function(){q=0;v=MAX_FRAMES_REEL_EASE;p=REEL_STATE_STOP};this.isReadyToStop=function(){return f};this.isHold=function(){return d};this._updateStart=function(){0===q&&h<NUM_REELS&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("start_reel",{volume:.3}));q++;q>v&&(q=0,v/=2,p++,w=x.y,y=w+SYMBOL_SIZE*
NUM_ROWS);var a=s_oTweenController.easeInBack(q,0,1,v),a=s_oTweenController.tweenValue(w,y,a);x.y=a};this._updateMoving=function(){q++;q>v&&(q=0,w=x.y,y=w+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(q,0,1,v),a=s_oTweenController.tweenValue(w,y,a);x.y=a};this._updateStopping=function(){q++;if(q>=v)k=!1,q=0,v=MAX_FRAMES_REEL_EASE,p=REEL_STATE_START,t=0,f=!1,c&&(c=!1,x.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(q,0,1,v),a=s_oTweenController.tweenValue(w,
y,a);x.y=a}};this.update=function(a){if(!1!==k&&(t++,t>n))if(d)a===h&&(k=!1,s_oGame.stopNextReel(),s_oGame.stopNextReel(),0===h&&s_oGame.increaseReelLoops());else switch(!1===f&&x.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(h,b),p){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,g,l,e)}
function CInterface(a,g,l){var e,k,f,c,d,h,b,n,t,p,q,v,w,y,A,x,u;this._init=function(a,g,l){var m=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-m.width/2-20;k=m.height/2+20;b=new CGfxButton(e,k,m,!0);b.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=b.getX()-m.width,c=m.height/2+20,q=new CToggle(f,c,s_oSpriteLibrary.getSprite("audio_icon")),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);m=s_oSpriteLibrary.getSprite("spin_but");n=new CTextButton(1094+
m.width/2,CANVAS_HEIGHT-m.height/2-4,m,TEXT_WIN+"\n0.00",FONT_GAME,"#ffde00",26);n.addEventListener(ON_MOUSE_UP,this._onSpin,this);m=s_oSpriteLibrary.getSprite("info_but");t=new CTextButton(320+m.width/2,CANVAS_HEIGHT-m.height/2-4,m,TEXT_INFO,FONT_GAME,"#ffffff",32);t.addEventListener(ON_MOUSE_UP,this._onInfo,this);m=s_oSpriteLibrary.getSprite("but_lines_bg");p=new CTextButton(490+m.width/2,CANVAS_HEIGHT-m.height/2-4,m,TEXT_LINES,FONT_GAME,"#ffffff",32);p.addEventListener(ON_MOUSE_UP,this._onAddLine,
this);m=s_oSpriteLibrary.getSprite("coin_but");v=new CTextButton(678+m.width/2,CANVAS_HEIGHT-m.height/2-4,m,TEXT_COIN,FONT_GAME,"#ffffff",32);v.addEventListener(ON_MOUSE_UP,this._onBet,this);m=s_oSpriteLibrary.getSprite("but_maxbet_bg");w=new CTextButton(866+m.width/2,CANVAS_HEIGHT-m.height/2-4,m,TEXT_MAX_BET,FONT_GAME,"#ffffff",32);w.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);A=new createjs.Text(TEXT_MONEY+"\n"+l.toFixed(2),"34px "+FONT_GAME,"#ffde00");A.x=450;A.y=46;A.textBaseline="alphabetic";
A.lineHeight=28;A.textAlign="center";s_oStage.addChild(A);u=new createjs.Text(NUM_PAYLINES,"24px "+FONT_GAME,"#ffde00");u.x=584;u.y=CANVAS_HEIGHT-77;u.shadow=new createjs.Shadow("#000",2,2,2);u.textAlign="center";u.textBaseline="alphabetic";s_oStage.addChild(u);y=new createjs.Text(a.toFixed(2),"24px "+FONT_GAME,"#ffde00");y.x=776;y.y=CANVAS_HEIGHT-77;y.shadow=new createjs.Shadow("#000",2,2,2);y.textAlign="center";y.textBaseline="alphabetic";s_oStage.addChild(y);x=new createjs.Text(TEXT_BET+": "+g.toFixed(2),
"24px "+FONT_GAME,"#ffde00");x.x=980;x.y=CANVAS_HEIGHT-77;x.shadow=new createjs.Shadow("#000",2,2,2);x.textAlign="center";x.textBaseline="alphabetic";s_oStage.addChild(x);m=s_oSpriteLibrary.getSprite("bet_but");d=[];a=new CBetBut(334+m.width/2,282+m.height/2,m,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);d[0]=a;a=new CBetBut(334+m.width/2,180+m.height/2,m,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);d[1]=a;a=new CBetBut(334+m.width/2,432+
m.height/2,m,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,3);d[2]=a;a=new CBetBut(334+m.width/2,114+m.height/2,m,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);d[3]=a;a=new CBetBut(334+m.width/2,502+m.height/2,m,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);d[4]=a;h=[];for(m=0;m<NUM_PAYLINES;m++)a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("payline_"+(m+1))),a.x=0,a.y=0,a.visible=!1,s_oStage.addChild(a),h[m]=
a;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){b.unload();b=null;n.unload();n=null;t.unload();t=null;p.unload();p=null;v.unload();v=null;w.unload();w=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;for(var a=0;a<NUM_PAYLINES;a++)d[a].unload();s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(f-a,d+c);b.setPosition(e-a,d+k)};this.refreshMoney=function(a){A.text=TEXT_MONEY+
"\n"+a.toFixed(2)};this.refreshBet=function(a){y.text=a.toFixed(2)};this.refreshTotalBet=function(a){x.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){u.text=a;for(var b=0;b<NUM_PAYLINES;b++)b<a?(d[b].setOn(),h[b].visible=!0):d[b].setOff();setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)h[a].visible=!1},1E3)};this.resetWin=function(){n.changeText("")};this.refreshWinText=function(a){n.changeText(TEXT_WIN+"\n"+a.toFixed(2))};this.showLine=function(a){h[a-1].visible=!0};this.hideLine=
function(a){h[a-1].visible=!1};this.hideAllLines=function(){for(var a=0;a<NUM_PAYLINES;a++)h[a].visible=!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)d[b].disable(a)};this.enableGuiButtons=function(){n.enable();w.enable();v.enable();p.enable();t.enable()};this.enableSpin=function(){n.enable();w.enable()};this.disableSpin=function(){n.disable();w.disable()};this.disableGuiButtons=function(){n.disable();w.disable();v.disable();p.disable();t.disable()};this._onBetLineClicked=function(a){this.refreshNumLines(a);
s_oGame.activateLines(a)};this._onExit=function(){s_oGame.onExit()};this._onSpin=function(){s_oGame.onSpin()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oInterface=this;this._init(a,g,l);return this}var s_oInterface=null;
function CPayTablePanel(){var a,g,l,e,k,f;this._init=function(){f=new createjs.Container;k=createBitmap(s_oSpriteLibrary.getSprite("paytable"));f.addChild(k);a=[];var c,d=450,h=106;a[0]=[];for(c=0;3>c;c++){var b=new createjs.Text("X"+(5-c),"bold 22px "+FONT_GAME,"#ffffff");b.textAlign="center";b.shadow=new createjs.Shadow("#000",1,1,2);b.x=d;b.y=h;b.textBaseline="alphabetic";f.addChild(b);a[0][c]=b;h+=30}d=660;h=106;a[1]=[];for(c=0;3>c;c++)b=new createjs.Text("X"+(5-c),"bold 22px "+FONT_GAME,"#ffffff"),
b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),a[1][c]=b,h+=30;d=850;h=106;a[2]=[];for(c=0;3>c;c++)b=new createjs.Text("X"+(5-c),"bold 22px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),a[2][c]=b,h+=30;d=1060;h=102;a[3]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",
1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),a[3][c]=b,h+=22;d=438;h=194;a[4]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),a[4][c]=b,h+=22;d=660;h=194;a[5]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline=
"alphabetic",f.addChild(b),a[5][c]=b,h+=22;d=850;h=194;a[6]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),a[6][c]=b,h+=22;d=1060;h=194;a[7]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),a[7][c]=
b,h+=22;g=[];d=480;h=106;g[0]=[];for(c=0;3>c;c++)b=new createjs.Text(s_aSymbolWin[0][4-c],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[0][c]=b,h+=30;d=686;h=106;g[1]=[];for(c=0;3>c;c++)b=new createjs.Text(s_aSymbolWin[1][4-c],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[1][c]=b,h+=30;d=880;h=106;
g[2]=[];for(c=0;3>c;c++)b=new createjs.Text(s_aSymbolWin[2][4-c],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[2][c]=b,h+=30;d=1080;h=102;g[3]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[3][4-c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[3][c]=b,h+=22;d=480;h=194;g[4]=[];for(c=0;4>c;c++)b=
new createjs.Text(s_aSymbolWin[4][4-c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[4][c]=b,h+=22;d=685;h=194;g[5]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[5][4-c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[5][c]=b,h+=22;d=880;h=194;g[6]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[6][4-
c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[6][c]=b,h+=22;d=1080;h=194;g[7]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[7][4-c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=h,b.textBaseline="alphabetic",f.addChild(b),g[7][c]=b,h+=22;l=new createjs.Text(TEXT_HELP_WILD,"22px "+FONT_GAME,"#ffff00");l.shadow=new createjs.Shadow("#000",
2,2,2);l.textAlign="center";l.lineHeight=22;l.lineWidth=200;l.x=636;l.y=286;f.addChild(l);e=new createjs.Text(TEXT_HELP_BONUS,"22px "+FONT_GAME,"#ffff00");e.shadow=new createjs.Shadow("#000",2,2,2);e.textAlign="center";e.lineHeight=22;e.lineWidth=190;e.x=980;e.y=294;f.addChild(e);f.visible=!1;s_oStage.addChild(f);var n=this;f.on("pressup",function(){n._onExit()})};this.unload=function(){var c=this;f.off("pressup",function(){c._onExit()});s_oStage.removeChild(f);for(var d=0;d<a.length;d++)f.removeChild(a[d]);
for(d=0;d<g.length;d++)f.removeChild(g[d])};this.show=function(){f.visible=!0};this.hide=function(){f.visible=!1};this.resetHighlightCombo=function(){for(var c=0;c<a.length;c++)for(var d=0;d<a[c].length;d++)a[c][d].color="#ffffff",g[c][d].color="#ffff00",createjs.Tween.removeTweens(g[c][d]),g[c][d].alpha=1};this.highlightCombo=function(a,d){8<a||(g[a-1][NUM_REELS-d].color="#ff0000",this.tweenAlpha(g[a-1][NUM_REELS-d],0))};this.tweenAlpha=function(a,d){var e=this;createjs.Tween.get(a).to({alpha:d},
200).call(function(){1===d?e.tweenAlpha(a,0):e.tweenAlpha(a,1)})};this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return f.visible};this._init()}
function CStaticSymbolCell(a,g,l,e){var k=-1,f,c,d,h;this._init=function(a,e,f,g){h=new createjs.Container;h.visible=!1;c=[];for(a=0;a<NUM_SYMBOLS;a++)e=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE),e.stop(),e.x=f,e.y=g,e.on("animationend",this._onAnimEnded,null,!1,{index:a}),h.addChild(e),c[a]=e,c[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
19]}};a=new createjs.SpriteSheet(a);d=new createSprite(a,"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);d.stop();d.x=f;d.y=g;h.addChild(d);s_oStage.addChild(h)};this.unload=function(){s_oStage.removeChild(h)};this.hide=function(){-1<k&&(d.gotoAndStop("static"),d.visible=!1,c[k].gotoAndPlay("static"),h.visible=!1)};this.show=function(a){d.gotoAndPlay("anim");d.visible=!0;for(var e=0;e<NUM_SYMBOLS;e++)c[e].visible=e+1===a?!0:!1;c[a-1].gotoAndPlay("anim");k=a-1;f=c[a-1].spriteSheet.getNumFrames();h.visible=!0};
this._onAnimEnded=function(a,d){c[d.index].currentFrame!==f&&(c[d.index].stop(),setTimeout(function(){c[d.index].gotoAndPlay(1)},100))};this.stopAnim=function(){c[k].gotoAndStop("static");c[k].visible=!1;d.gotoAndStop("static");d.visible=!1};this._init(a,g,l,e)}
function CTweenController(){this.tweenValue=function(a,g,l){return a+l*(g-a)};this.easeLinear=function(a,g,l,e){return l*a/e+g};this.easeInCubic=function(a,g,l,e){e=(a/=e)*a*a;return g+l*e};this.easeBackInQuart=function(a,g,l,e){e=(a/=e)*a;return g+l*(2*e*e+2*e*a+-3*e)};this.easeInBack=function(a,g,l,e){return l*(a/=e)*a*(2.70158*a-1.70158)+g};this.easeOutCubic=function(a,g,l,e){return l*((a=a/e-1)*a*a+1)+g}}
function CBonusPanel(){var a,g,l,e,k,f,c,d;this._init=function(){d=new createjs.Container;s_oStage.addChild(d);var a=createBitmap(s_oSpriteLibrary.getSprite("bonus_bg"));d.alpha=0;d.visible=!1;d.addChild(a);a={framerate:6,images:[s_oSpriteLibrary.getSprite("bonus_item")],frames:{width:BONUS_ITEM_WIDTH,height:BONUS_ITEM_HEIGHT},animations:{idle:[0],item_clicked:[1,14,"idle"]}};a=new createjs.SpriteSheet(a);l=[];for(var b=[{x:253,y:30},{x:577,y:118},{x:946,y:19},{x:262,y:305},{x:927,y:305}],e=0;5>e;e++){var g=
createSprite(a,"idle",0,0,BONUS_ITEM_WIDTH,BONUS_ITEM_HEIGHT);g.on("click",this._onBonusItemReleased,this,!1,e);g.x=b[e].x;g.y=b[e].y;g.visible=!1;d.addChild(g);l[e]=g}a=s_oSpriteLibrary.getSprite("bonus_prize");k=[];f=[];k[0]=createBitmap(a);k[0].x=300;k[0].y=CANVAS_HEIGHT-90;d.addChild(k[0]);b=new createjs.Text("100","44px "+FONT_GAME,"#ffff00");b.textAlign="left";b.x=k[0].x+a.width+10;b.y=k[0].y+a.height/2;b.textBaseline="middle";d.addChild(b);f.push(b);k[1]=createBitmap(a);k[1].x=600;k[1].y=CANVAS_HEIGHT-
90;d.addChild(k[1]);b=new createjs.Text("200","44px "+FONT_GAME,"#ffff00");b.textAlign="left";b.x=k[1].x+a.width+10;b.y=k[1].y+a.height/2;b.textBaseline="middle";d.addChild(b);f.push(b);k[2]=createBitmap(a);k[2].x=900;k[2].y=CANVAS_HEIGHT-90;d.addChild(k[2]);b=new createjs.Text("300","44px "+FONT_GAME,"#ffff00");b.textAlign="left";b.x=k[2].x+a.width+10;b.y=k[2].y+a.height/2;b.textBaseline="middle";d.addChild(b);f.push(b);c=[{x:440,y:129},{x:765,y:219},{x:1134,y:129},{x:450,y:405},{x:1114,y:405}]};
this.unload=function(){for(var a=0;5>a;a++)l[a].off("click",this._onBonusItemReleased)};this.show=function(c){a=!1;switch(c){case 3:e=BONUS_PRIZE[0];break;case 4:e=BONUS_PRIZE[1];break;case 5:e=BONUS_PRIZE[2];break;default:e=BONUS_PRIZE[0]}f[0].text=e[0]+"$";f[1].text=e[1]+"$";f[2].text=e[2]+"$";for(var b=0;b<c;b++)l[b].visible=!0;d.visible=!0;createjs.Tween.get(d).to({alpha:1},1E3)};this._onBonusItemReleased=function(c,b){a||(a=!0,g=e[s_aPrizeOccurence[Math.floor(Math.random()*s_aPrizeOccurence.length)]],
l[b].gotoAndPlay("item_clicked"),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("choose_bonus_item"),this.endBonus(b))};this.endBonus=function(a){new CScoreText("+"+g,c[a].x,c[a].y);setTimeout(function(){d.alpha=0;d.visible=!1;s_oGame.endBonus(g)},4E3)};this._init()}
function CScoreText(a,g,l){var e;this._init=function(a,f,c){e=new createjs.Text("00000","bold 50px "+FONT_GAME,"#ff0000");e.textAlign="center";e.text=a;e.x=f;e.y=c;e.alpha=0;e.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(e);var d=this;createjs.Tween.get(e).to({alpha:1},400,createjs.Ease.quadIn).call(function(){d.moveUp()})};this.moveUp=function(){var a=e.y-100,f=this;createjs.Tween.get(e).to({y:a},1E3,createjs.Ease.sineIn).call(function(){f.unload()})};this.unload=function(){s_oStage.removeChild(e)};
this._init(a,g,l)};
